name: tst

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish-reporting-tool-frontend:
    name: Publish Reporting Tool (client)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: azure/container-scan@v0
        with:
          image-name: ${{ env.REGISTRY }}/moja-global/flint_reporting.client:master

      # This ugly bit is necessary if you don't want your cache to grow forever
      # till it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
